default:
 host_r: localhost 
 host_w: localhost 
 user_r: 'mgsys'
 user_w: 'mgsys'
 pass_r: ''
 pass_w: ''
 db: 'mn_dot'
wwdev5003:
 DotServer0:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot'
 DotServer1:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot1'
 DotServer2:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot2'
 DotServer3:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot3'
 DotServer4:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot4'
 DotServer5:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot5'
 DotServer6:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot6'
 DotServer7:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot7'
 DotServer8:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot8'
 DotServer9:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot9'
 DotServer10:
  host_r: 'db_dot_s.dev.denagames.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_m.dev.denagames.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot10'
awdev0008:
 DotServer0:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot'
 DotServer1:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot1'
 DotServer2:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot2'
 DotServer3:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot3'
 DotServer4:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot4'
 DotServer5:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot5'
 DotServer6:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot6'
 DotServer7:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot7'
 DotServer8:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot8'
 DotServer9:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot9'
 DotServer10:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot10'
 DotServer11:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot11'
 DotServer12:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot12'
 DotServer13:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot13'
 DotServer14:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot14'
 DotServer15:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot15'
 DotServer16:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot16'
 DotServer17:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot17'
 DotServer18:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot18'
 DotServer19:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot19'
 DotServer20:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot20'
swdev0001:
 DotServer0:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot'
 DotServer1:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot1'
 DotServer2:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot2'
 DotServer3:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot3'
 DotServer4:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot4'
 DotServer5:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot5'
 DotServer6:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot6'
 DotServer7:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot7'
 DotServer8:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot8'
 DotServer9:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot9'
 DotServer10:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot10'
 DotServer11:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot11'
 DotServer12:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot12'
 DotServer13:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot13'
 DotServer14:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot14'
 DotServer15:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot15'
 DotServer16:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot16'
 DotServer17:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot17'
 DotServer18:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot18'
 DotServer19:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot19'
 DotServer20:
  host_r: 'db_dot_ww_s.dev.denagames-asia.local'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'db_dot_ww_m.dev.denagames-asia.local'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot20'
mgdev_dot_jp_web1:
 DotServer:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot'
 DotServer1:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot1'
 DotServer2:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot2'
 DotServer3:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot3'
 DotServer4:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot4'
 DotServer5:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot5'
 DotServer6:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot6'
 DotServer7:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot7'
 DotServer8:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot8'
 DotServer9:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot9'
 DotServer10:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot10'
 DotServer11:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot11'
 DotServer12:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot12'
mgdev_web1:
 DotServer:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot'
 DotServer1:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot1'
 DotServer2:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot2'
 DotServer3:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot3'
 DotServer4:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot4'
 DotServer5:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot5'
 DotServer6:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot6'
 DotServer7:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot7'
 DotServer8:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot8'
 DotServer9:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot9'
 DotServer10:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot10'
 DotServer11:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot11'
 DotServer12:
  host_r: 'localhost'
  user_r: 'mgsys_r'
  pass_r: ''
  host_w: 'localhost'
  user_w: 'mgsys'
  pass_w: ''
  db: 'mn_dot12'
wu0001:
 DotServer:
  host_r: 'db_dot_s.denagames-asia.local'
  host_w: 'db_dot_m.denagames-asia.local'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
wu0007:
 DotServer:
  host_r: 'db_dot_s.denagames-asia.local'
  host_w: 'db_dot_m.denagames-asia.local'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
mgdev_jenkins_smb:
 DotServer0:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot'
 DotServer1:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot1'
 DotServer2:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot2'
 DotServer3:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot3'
 DotServer4:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot4'
 DotServer5:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot5'
 DotServer6:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot6'
 DotServer7:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot7'
 DotServer8:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot8'
 DotServer9:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot9'
 DotServer10:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot10'
 DotServer11:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot11'
 DotServer12:
  host_r: '10.0.0.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.0.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot12'
jenkins_samba_JP:
 DotServer0:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot'
 DotServer1:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot1'
 DotServer2:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot2'
 DotServer3:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot3'
 DotServer4:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot4'
 DotServer5:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot5'
 DotServer6:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot6'
 DotServer7:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot7'
 DotServer8:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot8'
 DotServer9:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot9'
 DotServer10:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot10'
 DotServer11:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot11'
 DotServer12:
  host_r: '10.0.30.51'
  user_r: 'mgsys_r'
  pass_r: 'mgsys_r123'
  host_w: '10.0.30.51'
  user_w: 'mgsys'
  pass_w: 'mgsys123'
  db: 'mn_dot12'
au0001:
 DotServer:
  host_r: 'ad0004'
  host_w: 'ad0003'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
au2001:
 DotServer:
  host_r: 'ad0004'
  host_w: 'ad0003'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
ju0001:
 DotServer:
  host_r: 'db_dot_s.denagames-asia.local'
  host_w: 'db_dot_m.denagames-asia.local'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
ju0011:
 DotServer:
  host_r: 'db_dot_s.denagames-asia.local'
  host_w: 'db_dot_m.denagames-asia.local'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
ju0008:
 DotServer:
  host_r: 'db_dot_s.denagames-asia.local'
  host_w: 'db_dot_m.denagames-asia.local'
  user_r: 'mgsys_r'
  user_w: 'mgsys'
  pass_r: '********'
  pass_w: '********'
  db: 'mn_dot'
